import logo from "../assets/logo.png";
import download from "../assets/download.jpg";


export const dummyData = [
  {
    id: 1,
    name: "Product 1",
    description: "Description of product 1",
    image: logo,
    price: "20.00",
    discount: "10",
    available: "Yes",
  },
  {
    id: 2,
    name: "Product 2",
    description: "Description of product 2",
    image: logo,
    price: "30.00",
    discount: "15",
    available: "No",
  },
  {
    id: 3,
    name: "Product 3",
    description: "Description of product 3",
    image: download,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
  {
    id: 4,
    name: "Product 4",
    description: "Description of product 4",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "No",
  },
  {
    id: 5,
    name: "Product 5",
    description: "Description of product 5",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
  {
    id: 6,
    name: "Product 6",
    description: "Description of product 6",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "No",
  },
  {
    id: 7,
    name: "Product 7",
    description: "Description of product 7",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
  {
    id: 8,
    name: "Product 8",
    description: "Description of product 8",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "No",
  },
  {
    id: 9,
    name: "Product 9",
    description: "Description of product 9",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
  {
    id: 10,
    name: "Product 10",
    description: "Description of product 10",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "No",
  },
  {
    id: 11,
    name: "Product 11",
    description: "Description of product 11",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
  {
    id: 12,
    name: "Product 12",
    description: "Description of product 12",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "No",
  },
  {
    id: 13,
    name: "Product 13",
    description: "Description of product 13",
    image: logo,
    price: "40.00",
    discount: "5",
    available: "Yes",
  },
];
